package com.polar.habbohotel.items;

public enum InteractionType {
    NONE, GATE, POSTIT, MOODLIGHT, TROPHY, BED, BEDEFFECT, SCOREBOARD,
    VENDING_MACHINE, ALERT, ONE_WAY_GATE, LOVE_SHUFFLER, HABBO_WHEEL,
    DICE, BOTTLE, HOPPER, TELEPORT, POOL, ROLLER, FOOTBALL_GATE,
    PET1, PET2, PET3, PET4, PET5, PET6, PET7, PET8, PET9, PET10, PET11, PET12, PET13,
    FOOTBALL, FOOTBALL_GOAL_GREEN, FOOTBALL_GOAL_YELLOW, FOOTBALL_GOAL_BLUE, FOOTBALL_GOAL_RED,
    JUKEBOX, MUSIC_DISC, PUZZLE_BOX, TONER, GIFT, BACKGROUND, MANNEQUIN,
    GATE_VIP, GUILD_ITEM, GUILD_GATE, GUILD_FORUM, SLIDING_DOORS,
    TENT, TENT_SMALL, BADGE_DISPLAY, STACKTOOL, TELEVISION,
    WIRED_EFFECT, WIRED_TRIGGER, WIRED_CONDITION, WIRED_HIGHSCORE,
    WALLPAPER, FLOOR, LANDSCAPE, BADGE, CRACKABLE_EGG, EFFECT, DEAL,
    ATM_MACHINE, RP_NUKE, TRASH_CAN, HOUSE_SIGN, BASURERO, TRAGAMONEDAS,
    COCAINA, HEROINA, WEEDMATERIA, WEEDPORRO, BASURAENTREGA, MINERIA,
    DELIVERY_BOX, INFORMATION_TERMINAL, RENTABLE_SPACE, WHISPER_TILE,
    SHOWER, CAGAR, FARMING, CRAFTING, COMODIN, CARNEW;

    public static InteractionType getTypeFromString(String type) {
        if (type == null || type.isEmpty()) return NONE;
        try {
            return InteractionType.valueOf(type.toUpperCase());
        } catch (IllegalArgumentException e) {
            // Handle special cases if necessary
            return NONE;
        }
    }
}
