## Welcome Message Enabled
welcome.message.enabled=false
welcome.new.message.enabled=false
welcome.message.url=habbopages/bienvenida.txt

## DEBUG MODE
debug.enabled=false

## Targeted Enabled
targeted.offers.enabled=false

##Webhook
webhook.id=1250447910542250084
webhook.token=UR8YfMfrcFSaMShKoYB5Zar5EMprLMB_ow97bIN0ud4ytV8oMfkTyLBlMBMlvD9UYAzc

webhook.id.combat=1224516603517993153
webhook.token.combat=B0KeHklGyAxeuqInTcDDN7iGqKpOFXaouw4WwtJIkzUw-wMS_CWDU9bvNk6ch-tHqsKb