## Catalog Index
## Index 1
catalog.index.notice.1=¡Catálogo mejorado!
catalog.img.notice.1=catalogue/feature_cata_vert_oly16bundle4.png
catalog.link.notice.1=xmas16

## Index 2
catalog.index.notice.2=¡Obtenga su 0Km en la sala 69!
catalog.img.notice.2=catalogue/carro.png
catalog.link.notice.2=wired_custom

## Index 3
catalog.index.notice.3=¡Cambie de ropa en la sala 5!
catalog.img.notice.3=catalogue/catalog_easter2017.png
catalog.link.notice.3=valent_classic

## Index 4
catalog.index.notice.4=¡Ya disponibles los furnis públicos en Construcción!
catalog.img.notice.4=catalogue/catalog_publics.png
catalog.link.notice.4=publics_furni