## uberEmulator System Configuration File
## Must be edited for the server to work

## MySQL Configuration
db.hostname=127.0.0.1
db.port=3226
db.username=root
db.password=htrp2024$
db.name=hetosbeta

## MySQL pooling setup (controls amount of connections)
db.pool.minsize=10
db.pool.maxsize=250

## Game TCP/IP Configuration
game.tcp.bindip=0.0.0.0
game.tcp.port=2087
game.tcp.conlimit=100000
game.tcp.conperip=200
game.tcp.enablenagles=true

## MUS TCP/IP Configuration
mus.tcp.bindip=0.0.0.0
mus.tcp.port=3004
mus.tcp.allowedaddr=127.0.0.1;localhost;209.126.11.145;

## Client configuration
client.ping.enabled=1
client.ping.interval=20000
client.maxrequests=300

# WebSocket TCP/IP Configuration
ws.tcp.bindip=0.0.0.0
ws.tcp.port=2053
ws.certificate.protocol=wss
ws.certificate.pfx=hetos.pfx
ws.certificate.password=hetos22

##dd
hotel.name=HETOS
#Camera Configuration
Url_camera=https://swf.hetos.us/newfoto/
Camera_img_1=5235
Camera_img_2=202030
## Camera
camera.api=https://swf.hetos.us/newfoto/
camera.output.pictures=https://swf.hetos.us/newfoto/camera/
camera.url=https://swf.hetos.us/
camera.price.publish=10
camera.item.id=202030
camera.price.coins=2500
camera.price.duckets=0
url_youtube=https://hetos.us/youtubethumbnail.php?videoid=
## Welcome Message Enabled
welcome.message.enabled=false
welcome.new.message.enabled=false
welcome.message.url=habbopages/bienvenida.txt

Webhook=true
Webhook_Id=1250447910542250084
Webhook_Token=UR8YfMfrcFSaMShKoYB5Zar5EMprLMB_ow97bIN0ud4ytV8oMfkTyLBlMBMlvD9UYAzc
Webhook_avatar=https://hetos.us/img/logonew.png
Webhook_Username=⭐ Bot | HetosRP ⭐

## Targeted Enabled
targeted.offers.enabled=false