## Welcome Message Enabled
welcome.message.enabled=false
welcome.new.message.enabled=false
welcome.message.url=habbopages/bienvenida.txt

## DEBUG MODE
debug.enabled=false

## Targeted Enabled
targeted.offers.enabled=false